version: "3"

services:
  postgres:
   image: mdillon/postgis:11-alpine
   volumes:
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
   ports:
     - 5431:5432

  metabase:
    image: metabase/metabase
    volumes:
      - ./metabase-db:/metabase.db
    ports:
      - 3000:3000
    environment:
      - MUID=${UID}
      - MGID=${GID}
      - MB_DB_FILE=/metabase.db

  kanban-dash:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/code
    working_dir: /code/kanbandash
    environment:
      - KANBANDASH_DATABASE_URL=postgresql://postgres@postgres/kanban_metrics
